/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 knight.glb --transform 
Files: knight.glb [8.95MB] > /Users/gauntlet/ring/public/assets/models/knight-transformed.glb [1.58MB] (82%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/knight-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Knight" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Paladin_J_Nordstrom" geometry={nodes.Paladin_J_Nordstrom.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Paladin_J_Nordstrom_Helmet" geometry={nodes.Paladin_J_Nordstrom_Helmet.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Helmet.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Paladin_J_Nordstrom_Shield" geometry={nodes.Paladin_J_Nordstrom_Shield.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Shield.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Paladin_J_Nordstrom_Sword" geometry={nodes.Paladin_J_Nordstrom_Sword.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Sword.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/knight-transformed.glb')
